# Generated by Django 6.0.1 on 2026-01-15 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('max_participants', models.PositiveIntegerField(blank=True, help_text='Leave empty for unlimited participants.', null=True)),
                ('start_datetime', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField()),
                ('location_text', models.CharField(help_text='Physical location or short description.', max_length=255)),
                ('online_link', models.URLField(blank=True, help_text='Optional link for online meetups.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_meetups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_datetime'],
            },
        ),
    ]
